.github/workflows/pr_csharp.yml
Tadi ngga bisa ditest gara2 github actions down. Karena terlanjur merge baru ketauan makanya dibenerin di PR ini.
=> Fix Csharp CI

ruby/.rubocop.yml, ruby/Gemfile, ruby/Rakefile, ruby/lib/pehape/string/echo.rb, ruby/lib/pehape/string/index.rb, ruby/sig/php/func/ruby.rbs, ruby/spec/pehape/string/echo_spec.rb
Implementation
- string
unit test
- string
=> Add Echo to Ruby

ruby/lib/pehape/string/implode.rb, ruby/lib/pehape/string/index.rb, ruby/spec/pehape/string/implode_spec.rb
please review code function implode. om @ronnygunawan @aldy505 @elianiva
=> Add Implode To Ruby

clojure/src/pehape/core.clj, clojure/src/pehape/string/explode.clj, clojure/src/pehape/string/implode.clj, clojure/src/pehape/string/levenshtein.clj, clojure/test/pehape/string/explode_test.clj, clojure/test/pehape/string/implode_test.clj, clojure/test/pehape/string/levenshtein_test.clj
biar ga numpuk di 1 file
since clojure ga bisa multiple files per namespace, jadi pake cara re-export
=> refactor(clojure): restructure project namespace

.github/workflows/pr_clojure.yml, .github/workflows/pr_csharp.yml, .github/workflows/pr_go.yml, .github/workflows/pr_ruby.yml, .github/workflows/pr_rust.yml, .github/workflows/pr_typescript.yml, typescript/.eslintrc.json, typescript/package.json, typescript/pnpm-lock.yaml, typescript/src/index.ts, typescript/src/string/explode.test.ts, typescript/src/string/explode.ts, typescript/src/string/index.ts, typescript/tsconfig.json
sekalian ubah beberapa file di directory `.github/workflows` biar selalu jalan pas ke push semua ke master branch
=> ci: cleanup typescript configuration & setup ci

.github/workflows/pr_typescript.yml
=> ci: pnpm was not installed

go/explode.go
=> optimize the coverage from 96% to 100%.

typescript/src/string/implode.test.ts, typescript/src/string/implode.ts, typescript/src/string/index.ts
Baru ngerjain lagi. Boleh review nya @elianiva
=> feat(typescript): add implode implementation

go/levenshtein.go, go/levenshtein_test.go, go/readme.md
this algo gives O(m*n) complexity
issue #36
=> feat: add levenshtein implementation

.github/CODE_OF_CONDUCT.md, .github/FUNDING.yml, .github/PULL_REQUEST_TEMPLATE.md
Pull request template, so maintainers won't be confused about what language are they reading
=> chore: github metadata for pull request template and more

rust/src/string/explode.rs
=> fix(rust): fix clippy warning

go/md5.go, go/md5_test.go
- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number:
=> Feat-Go: add md5 function

go/lcfirst.go, go/lcrifst_test.go, go/strchr.go, go/strchr_test.go
- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number:
=> Feat-Go: add Lcfirst, Strchr function

go/trim.go, go/trim_test.go
- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number:
=> Feat-Go: add Trim function

csharp/Pehape/String/Md5.cs, csharp/Tests/String/Md5Tests.cs
- Programming langugage: C#
- Function(s) that I'm implementing: MD5
- Issue number: #11
=> Feat-C# Add md5 raw

typescript/src/string/count_chars.test.ts, typescript/src/string/count_chars.ts
- Programming langugage: TypeScript
- Function(s) that I'm implementing: count_chars
- Issue number: #18
=> feat(TypeScript): count_chars

go/str_replace.go, go/str_replace_test.go
- Programming langugage: 
- Function(s) that I'm implementing:
- Issue number: 
Ini condisinya banyak sekali, semangat reviewer! :)
=> Feat-Go: add StrReplace function

go/.gitignore, go/readme.md, go/str_shuffle.go, go/str_shuffle_test.go
- Programming langugage: golang
- Function(s) that I'm implementing: [str_shuffle](https://www.php.net/manual/en/function.str-shuffle)
- Issue number: #36
=> feat(str_shuffle): init

go/readme.md, go/strlen.go, go/strlen_test.go
- Programming langugage: `GO`
- Function(s) that I'm implementing: `strlen`
- Issue number: 
- [ v] I have created unit tests to support my implementation
- [v] I have created in-code documentation (or docstring) to document my code
- [v] (Optional) I have updated the README.md file to document the function I'm implementing
entah kenapa lucu liat implementasi nya cuman return `len()` wkwk
=> feat(go): strlen

go/readme.md, go/str_starts_with.go, go/str_starts_with_test.go
- Programming langugage:  `Go`
- Function(s) that I'm implementing: `str_starts_with()`
- Issue number: 
- [v] I have created unit tests to support my implementation
- [v] I have created in-code documentation (or docstring) to document my code
- [v] (Optional) I have updated the README.md file to document the function I'm implementing
=> feat(go): str_starts_with

go/readme.md, go/str_contains.go, go/str_contains_test.go
- Programming langugage: `GO`
- Function(s) that I'm implementing: `str_contains`
- Issue number: 
- [v] I have created unit tests to support my implementation
- [v] I have created in-code documentation (or docstring) to document my code
- [v] (Optional) I have updated the README.md file to document the function I'm implementing
=> feat(go): str_contains
